- name: update and upgrade APT packages
  hosts: all
  become: yes

  tasks:
   - name: "update and upgrade APT packages using apt"
     become: yes
     apt:
       name: apache2
       state: present
     when: ansible_distribution == 'Ubuntu'
     
   - name: "update and upgrade APT packages using yum"
     become: yes    
     yum:
       name: httpd
       state: present
     when: ansible_distribution == 'CentOS'
